version: "3.7"
services:
  db:
    image: "postgres:9.6"
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=johnskyi
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bloghub
    volumes:
      - ./../pgdata:/var/lib/postgresql/data
    networks:
      infrastructure:
        aliases:
          - postgres
networks:
  infrastructure:
    driver: "bridge"